### PR TITLE
Update SSE2NEON.h

### PR DESCRIPTION
**Pull request by p00380563**
add some fuctions for sse2neon, tested.

### CODE REVIEW

**Comment by p00380563** [comment]
OK

**Comment by p00380563** [comment]
update

**Comment by aflyhorse** [comment]
I recommend adding some comment lines.

**Comment by jserv** [comment]
The implementation of `_mm_cmpestrm` and `_mm_cmpestri` was incomplete. Other intrinsics were implemented and verified at [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon).

**Pull request closed without merging**
